MEZBELE/Models/Proje.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proje()
        {
            this.KullaniciProjeRol = new HashSet<KullaniciProjeRol>();
            this.Surec = new HashSet<Surec>();
        }
    
        public int ID { get; set; }
        public string ProjeAdi { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> DegistirmeTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<decimal> Butce { get; set; }
        public int ProjeSahibiID { get; set; }
        public Nullable<int> YoneticiID { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciProjeRol> KullaniciProjeRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surec> Surec { get; set; }
    }
}

MEZBELE/Controllers/ProjeController.cs
using MEZBELE.Models;
using System.Web.Mvc;
using System.Linq;
using System.Data.Entity;
using MEZBELE.ViewModels;
using System;
using System.Net;

namespace MEZBELE.Controllers
{
    /// <summary>
    /// Proje sisteminin kontrolcüsü.
    /// </summary>
    public class ProjeController : Controller
    {
        /// <summary>
        /// Veritabanı.
        /// </summary>
        private readonly MezbeleDBEntities db = new MezbeleDBEntities();

        /// <summary>
        /// ViewModel.
        /// </summary>
        private VM vm;

        /// <summary>
        /// Proje detay sayfası.
        /// </summary>
        /// <param name="projeKimligi">Detayları gösterilecek projenin kimliği</param>
        /// <returns>Sistemde kullanıcı varsa proje detay sayfasına yoksa karşılama sayfasına yönlendirir</returns>
        public ActionResult Detay(int projeKimligi)
        {
            if (Request.Cookies["KullaniciKimligi"] != null)
            {
                if (projeKimligi == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                int kullaniciID = int.Parse(Request.Cookies["KullaniciKimligi"].Value);

                vm = new VM();

                vm.Kullanici = (from k in db.Kullanici
                                where k.ID == kullaniciID
                                select k).SingleOrDefault();

                vm.AktifProje = (from p in db.Proje
                                 where p.ID == projeKimligi
                                 select p).SingleOrDefault();

                vm.Yonetici = (from y in db.Kullanici
                               where y.ID == vm.AktifProje.YoneticiID
                               select y).SingleOrDefault();

                vm.Calisanlar = (from c in db.Kullanici
                                 join k in db.KullaniciProjeRol on c.ID equals k.KullaniciID
                                 where k.ProjeID == vm.AktifProje.ID
                                 select c).Distinct().ToList();

                vm.Roller = (from r in db.Rol
                             where r.RolAdi != "Müşteri" && r.RolAdi != "Yönetici"
                             select r).ToList();

                return View(vm);
            }
            return RedirectToAction("Index", "Landing");
        }

        /// <summary>
        /// Süreç ekle sayfası.
        /// </summary>
        /// <param name="projeKimligi">Süreç eklenecek projenin kimliği</param>
        /// <param name="anaSurecKimligi">Süreç alt süreç olacaksa ana sürecinin kimliği</param>
        /// <returns>Sistemde kullanıcı varsa süreç ekleme sayfasına yoksa karşılama sayfasına yönlendirir</returns>
        public ActionResult SurecEkle(int projeKimligi, int anaSurecKimligi)
        {
            if (Request.Cookies["KullaniciKimligi"] != null)
            {
                vm = new VM();

                int kullaniciKimligi = Convert.ToInt32(Request.Cookies["KullaniciKimligi"].Value);

                vm.Kullanici = (from k in db.Kullanici
                                where k.ID == kullaniciKimligi
                                select k).SingleOrDefault();

                vm.AktifProje = (from p in db.Proje
                                 where p.ID == projeKimligi
                                 select p).SingleOrDefault();

                if (anaSurecKimligi != -1)
                {
                    vm.AktifSurec = (from s in db.Surec
                                     where s.ID == anaSurecKimligi
                                     select s).SingleOrDefault();
                }

                if (vm.Kullanici.ID == vm.AktifProje.YoneticiID)
                    return View(vm);
                else
                    return RedirectToAction("Index", "App");
            }
            return RedirectToAction("Index", "Landing");
        }

        /// <summary>
        /// Süreç detay sayfası.
        /// </summary>
        /// <param name="projeKimligi">Sürecin ait olduğu projenin kimliği</param>
        /// <param name="surecKimligi">Detayları gösterilecek sürecin kimliği</param>
        /// <returns>Sistemde kullanıcı varsa süreç detay sayfasına yoksa karşılama sayfasına yönlendirir</returns>
        public ActionResult SurecDetay(int projeKimligi, int surecKimligi)
        {
            if (Request.Cookies["KullaniciKimligi"] != null)
            {
                vm = new VM();

                int kullaniciKimligi = Convert.ToInt32(Request.Cookies["KullaniciKimligi"].Value);

                vm.Kullanici = (from k in db.Kullanici
                                where k.ID == kullaniciKimligi
                                select k).SingleOrDefault();

                vm.AktifSurec = (from s in db.Surec
                                 where s.ID == surecKimligi
                                 select s).SingleOrDefault();

                vm.AktifProje = (from p in db.Proje
                                 where p.ID == projeKimligi
                                 select p).SingleOrDefault();

                var kullaniciProjeRol = (from kpr in db.KullaniciProjeRol
                                         where kpr.KullaniciID == kullaniciKimligi && kpr.ProjeID == projeKimligi
                                         select kpr).SingleOrDefault();

                if (kullaniciProjeRol != null)
                    return View(vm);
                else
                    return RedirectToAction("Index", "App");
            }
            return RedirectToAction("Index", "Landing");
        }

        /// <summary>
        /// İş detay sayfası.
        /// </summary>
        /// <param name="projeKimligi">İşin ait olduğu projenin kimliği</param>
        /// <param name="surecKimligi">İşin ait olduğu sürecin kimliği</param>
        /// <param name="isKimligi">Detayları gösterilecek işin kimliği</param>
        /// <returns></returns>
        public ActionResult IsDetay(int projeKimligi, int surecKimligi, int isKimligi)
        {
            if (Request.Cookies["KullaniciKimligi"] != null)
            {
                vm = new VM();

                int kullaniciKimligi = Convert.ToInt32(Request.Cookies["KullaniciKimligi"].Value);

                vm.Kullanici = (from k in db.Kullanici
                                where k.ID == kullaniciKimligi
                                select k).SingleOrDefault();

                vm.AktifSurec = (from s in db.Surec
                                 where s.ID == surecKimligi
                                 select s).SingleOrDefault();

                vm.AktifProje = (from p in db.Proje
                                 where p.ID == projeKimligi
                                 select p).SingleOrDefault();

                vm.AktifIs = (from i in db.Is
                              where i.ID == isKimligi
                              select i).SingleOrDefault();

                vm.AtananKisi = (from a in db.IsKullanici
                                 where a.IsID == isKimligi
                                 select a).SingleOrDefault();

                var kullaniciProjeRol = (from kpr in db.KullaniciProjeRol
                                         where kpr.KullaniciID == kullaniciKimligi && kpr.ProjeID == projeKimligi
                                         select kpr).SingleOrDefault();

                if (kullaniciProjeRol != null)
                    return View(vm);
                else
                    return RedirectToAction("Index", "App");
            }
            return RedirectToAction("Index", "Landing");
        }

        /// <summary>
        /// Süreci kaydeder.
        /// </summary>
        /// <param name="surec">Kaydedilecek süreç</param>
        /// <returns>Kaydetme durumunu gönderir</returns>
        public JsonResult SurecKaydet(Surec surec)
        {
            try
            {
                int kullaniciKimligi = Convert.ToInt32(Request.Cookies["KullaniciKimligi"].Value);
                TimeSpan Sure = Convert.ToDateTime(surec.BitisTarihi) - Convert.ToDateTime(surec.BaslamaTarihi);
                surec.OlusturanKullaniciID = kullaniciKimligi;
                surec.Sure = Convert.ToInt32(Sure.TotalDays);
                surec.TamamlanmaOrani = 0;

                db.Surec.Add(surec);
                db.SaveChanges();

                return Json("başarılı");
            }
            catch
            {
                return Json("başarısız");
            }
        }

        /// <summary>
        /// Sistemdeki diğer kullanıcıları getirir.
        /// </summary>
        /// <returns>Kullanıcıları döndürür</returns>
        public JsonResult KullanicilariGetir()
        {
            try
            {
                int kullaniciKimligi = Convert.ToInt32(Request.Cookies["KullaniciKimligi"].Value);
                var kullanicilar = (from k in db.Kullanici
                                    where k.ID != kullaniciKimligi
                                    select new { Adi = k.Adi, Soyadi = k.Soyadi, ID = k.ID, Avatar = k.Avatar }).ToList();

                return Json(kullanicilar);
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Projeye kullanıcı atar.
        /// </summary>
        /// <param name="kpr">Eklenecek rol</param>
        /// <returns>Kayıt durumunu döndürür</returns>
        public JsonResult ProjeyeAta(KullaniciProjeRol kpr)
        {
            try
            {
                var rolDurum = (from r in db.KullaniciProjeRol
                                where r.KullaniciID == kpr.KullaniciID && r.ProjeID == kpr.ProjeID && r.RolID == kpr.RolID
                                select r).SingleOrDefault();
                if (rolDurum == null)
                {
                    db.KullaniciProjeRol.Add(kpr);
                    db.SaveChanges();
                    return Json("Kayıt başarılı.");
                }

MEZBELE/Views/Proje/IsDetay.cshtml
@model MEZBELE.ViewModels.VM
@{
    ViewBag.Title = "İş Detayı";
    Layout = "~/Views/Shared/App/_AppLayout.cshtml";
}
<br />
<div class="row">
    <nav>
        <div class="nav-wrapper blue-grey darken-1">
            <div class="col s12">
                <a href="/Proje/Detay?projeKimligi=@Model.AktifProje.ID" class="breadcrumb">@Model.AktifSurec.Proje.ProjeAdi </a>
                @if (Model.AktifSurec.Surec2 != null)
                {
                    <a href="/Proje/SurecDetay?projeKimligi=@Model.AktifProje.ID&surecKimligi=@Model.AktifSurec.Surec2.ID" class="breadcrumb">@Model.AktifSurec.Surec2.SurecAdi</a>
                }
                <a href="/Proje/SurecDetay?projeKimligi=@Model.AktifProje.ID&surecKimligi=@Model.AktifSurec.ID" class="breadcrumb">@Model.AktifSurec.SurecAdi</a>
                <a href="#!" class="breadcrumb">@Model.AktifIs.IsAdi</a>
                <a href="#!" class="breadcrumb">İş Detayı</a>
            </div>
        </div>
    </nav>
</div>

<div class="row">
    <div class="col s12">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <div class="row">
                    <div class="col s10">
                        <span class="card-title">@Model.AktifIs.IsAdi - Açıklama</span>
                        <div class="divider"></div><br />
                        <p>
                            @Model.AktifIs.Aciklama
                        </p>
                        <br />
                        <div class="divider"></div><br />
                        <div class="row">
                            <a class="waves-effect waves-light red btn" href="#İsiSil" onclick="isKimligiGetir(@Model.AktifIs.ID)">İşi Sil</a>
                            @if (Model.AktifIs.AktifMi == true)
                            {
                                if (Model.AtananKisi == null)
                                {
                                    <a class="waves-effect waves-light orange btn" href="#!" onclick="isiAl(@Model.AktifIs.ID)">İşi Al</a>
                                    if (Model.AktifProje.YoneticiID == Model.Kullanici.ID)
                                    {
                                        <a class="waves-effect waves-light deep-orange btn" href="#isAtaModal" onclick="isKimligiGetir(@Model.AktifIs.ID); KullaniciGetir(@Model.AktifProje.ID);">İşi Ata</a>
                                    }
                                }
                                else
                                {
                                    if (Model.Kullanici.ID == Model.AtananKisi.KullaniciID)
                                    {
                                        <a class="waves-effect waves-light orange btn" href="#!" onclick="isiBirak(@Model.AktifIs.ID)">İşi Bırak</a>
                                        <a class="waves-effect waves-light green btn" href="#!" onclick="isiTamamla(@Model.AktifIs.ID)">İşi Tamamla</a>
                                    }
                                }
                            }
                        </div>
                    </div>
                    <div class="col s2" style="padding-right:2.5rem;">
                        <div class="row">
                            <span class="badge teal white-text" style="width:100%;">@DateTime.Parse(Model.AktifIs.OlusturmaTarihi.Value.ToString()).ToShortDateString()</span>
                        </div>
                        <div class="row">
                            <span class="badge red white-text" style="width:100%;">@DateTime.Parse(Model.AktifIs.BitisTarihi.Value.ToString()).ToShortDateString()</span>
                        </div>
                        <div class="row">
                            <span class="badge deep-orange white-text" style="width:100%;">@Model.AktifIs.Surec.Proje.ProjeAdi</span>
                        </div>

                        @if (Model.AktifSurec.Surec2 != null)
                        {
                        <div class="row">
                            <span class="badge indigo darken-2 white-text" style="width:100%;">@Model.AktifSurec.Surec2.SurecAdi</span>
                        </div>
                        }
                        <div class="row">
                            <span class="badge orange white-text" style="width:100%;">@Model.AktifIs.Surec.SurecAdi</span>
                        </div>
                        <div class="row">
                            <span class="badge green white-text" style="width:100%;">@Model.AktifIs.IsKullanici.Count Çalışan</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- İş Silme Modal -->
<div id="İsiSil" class="modal">
    <div class="modal-content">
        <p>@Model.AktifIs.IsAdi adlı işi silmek istediğinizden emin misiniz?</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat" onclick="isiSil()">Sil</a>
        <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat">İptal</a>
    </div>
</div>
<!-- İş Silme Modal Sonu -->
<!-- İş Atama Modal -->
<div id="isAtaModal" class="modal">
    <div class="modal-content">
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="Kullanıcı" id="kullanicilar" class="autocomplete">
                <label for="kullanicilar">Kullanıcı Bul</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat" onclick="isiAta()">Ata</a>
    </div>
</div>
<!-- İş Atama Modal Sonu -->

<script>
    var isKimlik;
    function isKimligiGetir(isK) {
        isKimlik = isK;
    }

    function KullaniciGetir(projeKimlik) {
        var projeKimligi = projeKimlik;
        $.post("../Proje/ProjedekiKullanicilariGetir", { projeKimligi }, function (kullanicilar) {
            var veri = {};

            kullanicilar.forEach(function (k) {
                var anahtar = "#" + k.ID + " " + k.Adi + " " + k.Soyadi;
                var deger = k.Avatar;

                veri[anahtar] = deger;
            });

            $('input.autocomplete').autocomplete({
                data: veri
            });
        });
    }

    function isiSil() {
        var isKimligi = {
            isKimligi: isKimlik
        };
        console.log(isKimlik);
        $.post("/Proje/IsiSil", isKimligi, function (cevap) {
            if (cevap == "Başarılı.") {
                Materialize.toast('İş başarıyla silindi.', 3000, 'green rounded');
                window.location("/App/Index");
            } else {
                Materialize.toast('İş silinirken hata!', 3000, 'red rounded');
            }
        });
    }

    function isiAl(isKimligi) {
        var isKimligi = isKimligi;
        $.post("/Proje/IsiAl", { isKimligi}, function (cevap) {
            if (cevap == "Başarılı.") {
                Materialize.toast('İşi üzerine aldın.', 3000, 'green rounded');
                window.location.reload(true);
            } else {
                Materialize.toast('İşi üstüne alamadın!', 3000, 'red rounded');
            }
        });
    }

    function isiBirak(isKimligi) {
        var isKimligi = isKimligi;
        $.post("/Proje/IsiBirak", { isKimligi}, function (cevap) {
            if (cevap == "Başarılı.") {
                Materialize.toast('İşi bıraktın.', 3000, 'green rounded');
                window.location.reload(true);
            } else {
                Materialize.toast('İşi bırakamadın!', 3000, 'red rounded');
            }
        });
    }

    function isiAta() {
        var idMetin = $('input.autocomplete').val();
        var kID = idMetin.substring(idMetin.indexOf("#") + 1, idMetin.indexOf(" "));
        var ik = {
            IsID: isKimlik,
            KullaniciID: kID
        };
        $.post("/Proje/IsiAta", ik, function (cevap) {
            if (cevap == "Başarılı.") {
                Materialize.toast('İşi atama başarılı.', 3000, 'green rounded');
                window.location.reload(true);
            } else {
                Materialize.toast('İşi atama başarısız!', 3000, 'red rounded');
            }
        });
    }

    function isiTamamla(isKimlik) {
        var isKimligi = isKimlik;
        $.post("/Proje/IsiTamamla", { isKimligi }, function (cevap) {
            if (cevap == "Başarılı.") {
                Materialize.toast('İş tamamlandı.', 3000, 'green rounded');
                window.location.reload(true);
            } else {
                Materialize.toast('İş tamamlama kayıt hatası!', 3000, 'red rounded');
            }
        });
    }
</script>

MEZBELE/Views/Proje/SurecEkle.cshtml
@model MEZBELE.ViewModels.VM
@{
    ViewBag.Title = "Süreç Ekle";
    Layout = "~/Views/Shared/App/_AppLayout.cshtml";
}
<br />

<div class="row">
    <nav>
        <div class="nav-wrapper blue-grey darken-1">
            <div class="col s12">
                <a href="/App/Projeler" class="breadcrumb">Projeler</a>
                @Html.ActionLink(Model.AktifProje.ProjeAdi, "Detay", "Proje", new { projeKimligi = Model.AktifProje.ID }, new { @class = "breadcrumb" })
                <a class="breadcrumb">Süreç Ekle</a>
            </div>
        </div>
    </nav>
</div>

<div class="row">
    <div class="card blue-grey darken-1">
        <div class="card-content white-text">
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s6">
                            <input id="SurecAdi" type="text" name="Süreç Adı">
                            <label for="SurecAdi" class="white-text">Süreç Adı</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <textarea id="SurecAciklama" name="Açıklama" class="materialize-textarea"></textarea>
                            <label for="SurecAciklama" class="white-text">Açıklama</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s6">
                            <input id="BaslangicTarihi" type="date" class="datepicker" placeholder="Başlangıç Tarihi" name="Başlangıç Tarihi">
                        </div>
                        <div class="input-field col s6">
                            <input id="BitisTarihi" type="date" class="datepicker" placeholder="Bitiş Tarihi" name="Bitiş Tarihi">
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <select id="Oncelik" name="Öncelik">
                                <option value="1">Düşük</option>
                                <option value="2">Orta</option>
                                <option value="3">Yüksek</option>
                            </select>
                            <label class="white-text">Öncelik</label>
                        </div>
                    </div>
                    <div class="row col s12">
                        @if (Model.AktifSurec == null)
                        {
                            <a class="waves-effect waves-light btn" onclick="SureciKaydet(@Model.AktifProje.ID, -1)">Kaydet</a>
                        }
                        else
                        {
                            <a class="waves-effect waves-light btn" onclick="SureciKaydet(@Model.AktifProje.ID, @Model.AktifSurec.ID)">Kaydet</a>
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function SureciKaydet(projeID, anaSurecKimligi) {
        var kontrol = true;
        $('input').each(function () {
            if ($.trim($(this).val()) == "") {
                Materialize.toast(this.name + ' alanı boş bırakılamaz!', 3000, 'red rounded');
                kontrol = false;
                $(this).addClass("invalid");
            } else {
                $(this).removeClass("invalid");
            }
        });

        if ($.trim($('#SurecAciklama').val()) == "") {
            Materialize.toast('Açıklama alanı boş bırakılamaz!', 3000, 'red rounded');
            kontrol = false;
            $('#SurecAciklama').addClass("invalid");
        } else {
            $('#SurecAciklama').removeClass("invalid");
        }

        if($("#BitisTarihi").val() < $("#BaslangicTarihi").val()) {
            Materialize.toast('Bitiş tarihi başlangıç tarihinden küçük olamaz!', 3000, 'red rounded');
            kontrol = false;
            $('#BitisTarihi').addClass("invalid");
            $('#BaslangicTarihi').addClass("invalid");
        } else {
            $('#BitisTarihi').removeClass("invalid");
            $('#BaslangicTarihi').removeClass("invalid");
        }

        if (kontrol) {
            var surec = {
                SurecAdi: $("#SurecAdi").val(),
                Aciklama: $("#SurecAciklama").val(),
                BaslamaTarihi: $("#BaslangicTarihi").val(),
                BitisTarihi: $("#BitisTarihi").val(),
                Oncelik: $("#Oncelik").val(),
                ProjeID: projeID
            };

            if (anaSurecKimligi != -1) {
                surec.AnaSurecID = anaSurecKimligi;
            }

            $.post("../Proje/SurecKaydet", surec, function (cevap) {
                if (cevap === "başarılı") {
                    Materialize.toast('Süreç başarıyla eklendi!', 3000, 'green rounded');
                    window.location = "/Proje/Detay?projeKimligi=" + @Model.AktifProje.ID;
                } else {
                    Materialize.toast('Süreç ekleme başarısız!', 3000, 'red rounded');
                }
            });
        }
    }
</script>